### ISSUE TITLE
📷 Add a screenshot to the readme

### ISSUE THREAD

**Issue by Squarific** [becodeorg/pwojekte#16]
A screenshot would be nice to quickly understand if this is as cool as it sounds.

**Comment by leny** [comment]
I have the project running now (was working on it).

Give me a moment, I'll do it right away.

**Comment by leny** [comment]
_BOOM_, done. 😜

Thanks for the question 👍

**Comment by leny** [comment]
Hope that, with the screenshots, it's even _cooler_ than that! 😇
